apiVersion: v1
kind: Pod
metadata:
  name: newrelic-troubleshooter
spec:
  containers:
  - name: newrelic-troubleshooter
    image: docker.io/spolfliet/newrelic-troubleshooter:latest
    ports:
    - containerPort: 80
    env:
    - name: NRIA_LICENSE_KEY
      value: <NEW_RELIC_LICENSE_KEY>
    - name: NEW_RELIC_REGION
      value: US
    - name: HTTP_PROXY
      value:
    volumeMounts:
      - name: varlog
        mountPath: /var
  volumes:
    - name: varlog
      hostPath:
        path: /var